name:                diskmat
version:             0.1.0.0
license:             BSD3
author:              "Camilla Rygh"
copyright:           "2019 Camilla Rygh"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  diskmat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - diskmat
